version: 2
updates:
  - directory: "src/backend/Altinn.Receipt"
    package-ecosystem: "nuget"
    schedule:
      interval: "daily"
      ##day: "thursday"
      time: "07:00"
      timezone: "Europe/Oslo"

## Test
  - directory: "test"
    package-ecosystem: "nuget"
    schedule:
      interval: "daily"
      ##day: "thursday"
      time: "07:00"
      timezone: "Europe/Oslo"

## Dockerfile
  - directory: "/"
    package-ecosystem: "docker"
    schedule:
      interval: "daily"
      ##day: "thursday"
      time: "07:00"
      timezone: "Europe/Oslo"

## Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
      ##day: "thursday"
      time: "07:00"
      timezone: "Europe/Oslo"
    open-pull-requests-limit: 10
